# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Tareena Musaddiq 
email: tmusaddiq1@gsu.edu
description: tmusaddiq1@gsu.edu
baseurl: "" # the subpath of your site, e.g. /blog
github_username:  tareena 
linkedin_username: tareena-musaddiq 
twitter_username: tareenamusaddiq 

# Build settings
markdown: kramdown
